#' Roxygenheader
#'
#' Update files generated by ospsuite.bmlm
#'
#' This script converts files generated with old package versions
#'              so that they can run with newer versions by updating the scaling method.
#'
#' @param projectConfiguration A list containing configuration settings for the project.
#' @return None
#' @export
#' @family configuration
convertVersionBMLM <- function(projectConfiguration) {
  runFolders <- list.dirs(
    path = file.path(projectConfiguration$outputFolder, "BMLM"),
    recursive = FALSE
  )

  for (folder in runFolders) {
    checkAndUpdateScalingMethod(folder)
    convertScaledToUnscaledParams(folder)
  }

  return(invisible())
}
#' Check and Update Scaling Method
#'
#' Version 0.1.9 introdcuded a `scalingMethod`, which was saved in the status files.
#' This function checks for the presence of the 'scalingMethod' in status files
#' within a specified folder. If it is not present, it updates the status file
#' by adding the `scalingMethod` available for older versions
#' and initializing the 'outsideRangeCounter'.
#'
#' @param folder A character string specifying the path to the folder containing
#'               the status files.
#' @return None
checkAndUpdateScalingMethod <- function(folder) {
  statusFiles <- list.files(path = folder, pattern = "Status.RDS")

  for (sFile in statusFiles) {
    status <- readRDS(file = file.path(folder, sFile))

    if (!"scalingMethod" %in% names(status)) {
      status[["scalingMethod"]] <- ospsuite.bmlm::SCALINGMETHOD$logsig
      status[["outsideRangeCounter"]] <- 0

      saveRDS(object = status, file = file.path(folder, sFile))

      message(paste("Updated scalingMethod in file:", sFile, "for run", folder))
    }
    convergence <- fread(file = file.path(folder, "convergence.csv"))
    if (!"outsideRangeCounter" %in% names(convergence)) {
      convergence[, outsideRangeCounter := 0]
      setcolorder(convergence, neworder = "outsideRangeCounter", before = "event")

      fwrite(convergence, file = file.path(folder, "convergence.csv"))
      message(paste("Add outsideRangeCounter to convergence.csv for run", folder))
    }
  }

  return(invisible())
}

#' Convert Scaled to Unscaled Parameters
#'
#' Version 0.2.0 changed the storage format of parameters in status files from scaled to unscaled.
#' This function checks if status files contain scaled parameters and converts them to unscaled format.
#' It also adds a version marker to indicate the conversion has been done.
#'
#' @param folder A character string specifying the path to the folder containing the status files.
#' @return None
#' @keywords internal
#' @noRd
convertScaledToUnscaledParams <- function(folder) {
  # Check if conversion has already been done
  versionFile <- file.path(folder, "package_version.txt")
  if (file.exists(versionFile)) {
    savedVersion <- readLines(versionFile, warn = FALSE)[1]
    # If version is 0.2.0 or higher, conversion already done
    if (compareVersion(savedVersion, "0.2.0") >= 0) {
      return(invisible())
    }
  }

  statusFiles <- list.files(path = folder, pattern = "optimStatus.RDS$")

  # Need to load the data tables to perform unscaling
  priorFile <- file.path(folder, "prior.csv")
  startValuesFile <- file.path(folder, "startValues.csv")

  if (!file.exists(priorFile)) {
    message(paste("Cannot convert parameters - prior.csv not found in", folder))
    return(invisible())
  }

  dtPrior <- fread(priorFile)
  dtStartValues <- if (file.exists(startValuesFile)) fread(startValuesFile) else data.table()

  for (sFile in statusFiles) {
    status <- readRDS(file = file.path(folder, sFile))

    # Check if params exist and scalingMethod is defined
    if ("params" %in% names(status) && "scalingMethod" %in% names(status)) {
      # Check if this looks like it needs conversion by trying to detect scaled vs unscaled
      # Scaled params for hardBounds should be between 0 and 1
      # We'll check if ALL params are in (0,1) range which suggests they're scaled
      if (status$scalingMethod == SCALINGMETHOD$hardBounds) {
        allInRange <- all(status$params > 0 & status$params < 1)
        
        if (allInRange) {
          # These appear to be scaled params, convert to unscaled
          unscaleParamToValue <- getUnscaleFunction(status$scalingMethod)
          
          # Create a temporary dtList structure
          dtList <- list(prior = dtPrior, startValues = dtStartValues)
          
          # Use setParameterToTables to convert scaled to unscaled
          dtList <- setParameterToTables(
            dtList = dtList,
            params = status$params,
            scalingMethod = status$scalingMethod
          )
          
          # Extract the unscaled values
          status$params <- getUnscaledParams(
            dtPrior = dtList$prior,
            dtStartValues = dtList$startValues,
            optimizationGroup = "both"
          )
          
          # Save the updated status
          saveRDS(object = status, file = file.path(folder, sFile))
          
          message(paste("Converted scaled to unscaled parameters in file:", sFile, "for run", folder))
        }
      } else if (status$scalingMethod == SCALINGMETHOD$logsig) {
        # For logsig, scaled params are typically in a wider range around [-20, 20]
        # But it's harder to detect, so we'll check if params are outside typical value ranges
        # We'll use a heuristic: if most params are in [-20, 20] range, they're likely scaled
        inScaledRange <- sum(status$params >= -20 & status$params <= 20) / length(status$params)
        
        if (inScaledRange > 0.8) {  # If 80%+ are in this range, likely scaled
          # Convert to unscaled
          dtList <- list(prior = dtPrior, startValues = dtStartValues)
          
          dtList <- setParameterToTables(
            dtList = dtList,
            params = status$params,
            scalingMethod = status$scalingMethod
          )
          
          status$params <- getUnscaledParams(
            dtPrior = dtList$prior,
            dtStartValues = dtList$startValues,
            optimizationGroup = "both"
          )
          
          saveRDS(object = status, file = file.path(folder, sFile))
          
          message(paste("Converted scaled to unscaled parameters in file:", sFile, "for run", folder))
        }
      }
    }
  }

  return(invisible())
}
