#' Roxygenheader
#'
#' Update files generated by ospsuite.bmlm
#'
#' This script converts files generated with old package versions
#'              so that they can run with newer versions by updating the scaling method.
#'
#' @param projectConfiguration A list containing configuration settings for the project.
#' @return None
#' @export
#' @family configuration
convertVersionBMLM <- function(projectConfiguration) {
  runFolders <- list.dirs(
    path = file.path(projectConfiguration$outputFolder, "BMLM"),
    recursive = FALSE
  )

  for (folder in runFolders) {
    checkAndUpdateScalingMethod(folder)
  }

  return(invisible())
}
#' Check and Update Scaling Method
#'
#' Version 0.1.9 introdcuded a `scalingMethod`, which was saved in the status files.
#' This function checks for the presence of the 'scalingMethod' in status files
#' within a specified folder. If it is not present, it updates the status file
#' by adding the `scalingMethod` available for older versions
#' and initializing the 'outsideRangeCounter'.
#'
#' @param folder A character string specifying the path to the folder containing
#'               the status files.
#' @return None
checkAndUpdateScalingMethod <- function(folder) {
  statusFiles <- list.files(path = folder, pattern = "Status.RDS")

  for (sFile in statusFiles) {
    status <- readRDS(file = file.path(folder, sFile))

    if (!"scalingMethod" %in% names(status)) {
      status[["scalingMethod"]] <- ospsuite.bmlm::SCALINGMETHOD$logsig
      status[["outsideRangeCounter"]] <- 0

      saveRDS(object = status, file = file.path(folder, sFile))

      message(paste("Updated scalingMethod in file:", sFile, "for run", folder))
    }
    convergence <- fread(file = file.path(folder, "convergence.csv"))
    if (!"outsideRangeCounter" %in% names(convergence)) {
      convergence[, outsideRangeCounter := 0]
      setcolorder(convergence, neworder = "outsideRangeCounter", before = "event")

      fwrite(convergence, file = file.path(folder, "convergence.csv"))
      message(paste("Add outsideRangeCounter to convergence.csv for run", folder))
    }
  }

  return(invisible())
}
